server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Compression gzip
    gzip on;
    gzip_types text/html text/css application/javascript application/json;

    # Cache des assets statiques
    location ~* \.(html|css|js)$ {
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Health check Nginx
    location /nginx-health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
